### ISSUE TITLE
I'm using webpack with the Titanium CLI -- where does the config.js go?

### ISSUE THREAD

**Issue by jasonkneen** [appcelerator/appcd-plugin-webpack#24]
Th README  talks about changing the timeout in the `appcd` `config.js` file but I’m using the Ti CLI — so where could I put the `inactivityTimeout` setting? could it be put in the project folder? or in the ~/.titanium/config.js file.

Would be great if we could have a local project config file.

**Comment by janvennemann** [comment]
We already talked on Slack but just in case someone else finds this:

It doesn't matter which CLI you use, everything is controlled by the Appc Daemon. So the config goes into the Daemon config override at `~/.appcelerator/appcd/config.json`. There is a known bug in the latest Daemon version which sometimes prevents the config system from properly merging your custom config. In that case try running `appcd restart` and the config should get properly merged.
